# Generated by Django 4.2 on 2023-04-22 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vegan', models.BooleanField()),
                ('vegetarian', models.BooleanField()),
                ('halal', models.BooleanField()),
                ('glutenFree', models.BooleanField()),
                ('lactoseIntolerance', models.BooleanField()),
                ('dairyFree', models.BooleanField()),
                ('nutAllergy', models.BooleanField()),
                ('Other', models.TextField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='inventory.user_info')),
            ],
        ),
    ]
