# Generated by Django 4.2 on 2023-04-22 20:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientsGeneric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userID', to='inventory.user_info')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientsSpecific',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfPurchase', models.DateField()),
                ('expiryDate', models.DateField()),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('ingredientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientID', to='inventory.ingredientsgeneric')),
                ('inventoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryID', to='inventory.inventory')),
            ],
        ),
    ]
