# Generated by Django 4.2 on 2023-04-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_ingredientsgeneric_inventory_ingredientsspecific'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='total_waste',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
