# Generated by Django 4.2 on 2023-04-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_user_info_user_alter_preferences_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='fName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='lName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='phoneNumber',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
