# Generated by Django 4.2 on 2023-04-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_user_info_dob_alter_user_info_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsspecific',
            name='dateOfPurchase',
            field=models.DateField(auto_now=True),
        ),
    ]
